[0m15:31:22.147448 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C682047B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C6822C8150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C681CB4450>]}


============================== 15:31:22.155417 | 8011fffe-b9b0-4ddd-a793-ebd8ed206c93 ==============================
[0m15:31:22.155417 [info ] [MainThread]: Running with dbt=1.5.4
[0m15:31:22.156462 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\shash\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m15:31:39.541956 [debug] [MainThread]: Starter project path: C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m15:31:56.439167 [error] [MainThread]: Encountered an error:

[0m15:31:56.444165 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\main.py", line 459, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 306, in run
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 230, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 166, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m15:31:56.446166 [debug] [MainThread]: Command `dbt init` failed at 15:31:56.446166 after 34.34 seconds
[0m15:31:56.447165 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C682053150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C681C98C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C681C99D90>]}
[0m15:31:56.447165 [debug] [MainThread]: Flushing usage events
[0m15:35:30.379802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB97CE5D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB97AD190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB97ADC50>]}


============================== 15:35:30.383807 | c8af81c9-25b4-415a-9a46-854e31ded846 ==============================
[0m15:35:30.383807 [info ] [MainThread]: Running with dbt=1.7.1
[0m15:35:30.385807 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\shash\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:35:36.595428 [info ] [MainThread]: A project called dbt_demo already exists here.
[0m15:35:36.597431 [debug] [MainThread]: Command `dbt init` succeeded at 15:35:36.596425 after 6.29 seconds
[0m15:35:36.598431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB97DB390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB4169810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB3FD8ED0>]}
[0m15:35:36.599444 [debug] [MainThread]: Flushing usage events
[0m15:35:43.653492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C42F54D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C42F939D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026C42F92650>]}


============================== 15:35:43.657484 | 8f41bd3b-f410-4a42-a203-490831dcde41 ==============================
[0m15:35:43.657484 [info ] [MainThread]: Running with dbt=1.7.1
[0m15:35:43.657484 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\shash\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m15:35:46.911936 [debug] [MainThread]: Starter project path: C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\include\starter_project
[0m15:35:46.943485 [info ] [MainThread]: 
Your new dbt project "dbt_demos" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:35:46.945468 [info ] [MainThread]: Setting up your profile.
[0m07:11:07.413935 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F18FCDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F1FBE6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F17913D0>]}


============================== 07:11:07.419124 | 8fde1c84-33c9-4efd-85bd-fe8d697b23c0 ==============================
[0m07:11:07.419124 [info ] [MainThread]: Running with dbt=1.5.4
[0m07:11:07.420124 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\shash\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m07:11:07.421123 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m07:11:07.422123 [debug] [MainThread]: Command `dbt run` failed at 07:11:07.422123 after 0.05 seconds
[0m07:11:07.422123 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F190C250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F1FBE6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247F1FBE350>]}
[0m07:11:07.422123 [debug] [MainThread]: Flushing usage events
[0m13:20:46.280029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC44910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC44D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC44C10>]}


============================== 13:20:46.290488 | 6e438045-206c-41aa-90ff-ef8e764a59e7 ==============================
[0m13:20:46.290488 [info ] [MainThread]: Running with dbt=1.7.1
[0m13:20:46.293487 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '~/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:20:46.296017 [info ] [MainThread]: Creating dbt configuration folder at ~/.dbt
[0m13:21:39.476138 [debug] [MainThread]: Starter project path: C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\include\starter_project
[0m13:21:39.527806 [info ] [MainThread]: 
Your new dbt project "syne_dataplatform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:21:39.530809 [info ] [MainThread]: Setting up your profile.
[0m13:23:38.423994 [error] [MainThread]: Encountered an error:
[Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'
[0m13:23:38.428002 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 168, in create_profile_from_profile_template
    self.write_profile(profile, profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 158, in write_profile
    with open(profiles_filepath, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'

[0m13:23:38.435550 [debug] [MainThread]: Command `dbt init` failed at 13:23:38.434530 after 172.21 seconds
[0m13:23:38.436566 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC31E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC46250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A3AFC45090>]}
[0m13:23:38.439555 [debug] [MainThread]: Flushing usage events
[0m13:23:46.359294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DC18528B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DC18528B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001DC18528ED0>]}


============================== 13:23:46.367489 | e8aa03c4-83ae-4c84-81a7-f816bb565189 ==============================
[0m13:23:46.367489 [info ] [MainThread]: Running with dbt=1.7.1
[0m13:23:46.369490 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '~/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:30:43.667792 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9AE84F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9AE84F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9AE85050>]}


============================== 13:30:43.672183 | a4565811-191c-4496-987f-acdc839c9ed8 ==============================
[0m13:30:43.672183 [info ] [MainThread]: Running with dbt=1.7.1
[0m13:30:43.675422 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '~/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:30:50.014564 [debug] [MainThread]: Starter project path: C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\include\starter_project
[0m13:30:50.048912 [info ] [MainThread]: 
Your new dbt project "syne_dataplatform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:30:50.052422 [info ] [MainThread]: Setting up your profile.
[0m13:33:55.945466 [error] [MainThread]: Encountered an error:
[Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'
[0m13:33:55.947996 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 168, in create_profile_from_profile_template
    self.write_profile(profile, profile_name)
  File "C:\Users\shash\OneDrive\My Learning\Env_Setup\l3_framework\dbt\venv\Lib\site-packages\dbt\task\init.py", line 158, in write_profile
    with open(profiles_filepath, "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~\\.dbt\\profiles.yml'

[0m13:33:55.953027 [debug] [MainThread]: Command `dbt init` failed at 13:33:55.953027 after 192.33 seconds
[0m13:33:55.954029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9AE859D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9AE71F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F9A713190>]}
[0m13:33:55.955038 [debug] [MainThread]: Flushing usage events
